# workflow 的名称。如果省略则默认为当前 workflow 的文件名
name: deployment

on:
  push:
    branches: 
      - main

jobs:
  docs:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2.3.4

    # 设置 node.js 运行环境
    - name: Setup node
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '14'

    # 设置缓存依赖，加快下次安装依赖的速度
    - name: Cache node modules
      uses: actions/cache@v2.1.3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

    # 安装依赖
    - name: Install dependencies
      run: yarn install

    # 构建文件
    - name: Generate files
      run: yarn build

    # 将构建后的文件推送到 gh-pages
    - name: Push to gh-pages
      env:
        # 填写项目所在仓库地址
        GITHUB_REPO: https://github.com/danicachen/vuetify-calendar
      run: |
        cd ./dist
        git init
        git config --local user.name "LeoKu"
        git config --local user.email "czc12580520@gmail.com"
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@$GITHUB_REPO" HEAD:gh-pages